apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    name: sabnzbd
    namespace: sabnzbd
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.111.181.18
    clusterIPs:
    - 10.111.181.18
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32151
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: sabnzbd
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations: {}
    generation: 8
    name: sabnzbd
    namespace: sabnzbd
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sabnzbd
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: '2026-04-20T20:04:48+02:00'
        creationTimestamp: null
        labels:
          app: sabnzbd
      spec:
        containers:
        - image: linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          name: sabnzbd
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /downloads
            name: downloads
        dnsPolicy: ClusterFirst
        initContainers:
        - args:
          - "CONFIG_FILE=/config/sabnzbd.ini\nif [ -f \"$CONFIG_FILE\" ]; then\n \
            \ grep -q sabnzbd.local.lan \"$CONFIG_FILE\" || sed -i 's/^host_whitelist\
            \ = /host_whitelist = sabnzbd.local.lan,/' \"$CONFIG_FILE\"\nfi\n"
          command:
          - /bin/sh
          - -c
          image: busybox
          imagePullPolicy: Always
          name: patch-host-whitelist
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /media/sene/vidjo
            name: downloads
        nodeSelector:
          kubernetes.io/hostname: k8s-master
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - hostPath:
            path: /media/sene/vidjo
            type: Directory
          name: downloads
kind: List
metadata:
  resourceVersion: ''
