apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    labels:
      app: pihole
      cluster: home-lab
      date: '2026-04-09'
      environment: production
      managed-by: terraform
    name: pihole
    namespace: pihole
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.98.90.204
    clusterIPs:
    - 10.98.90.204
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns-udp
      nodePort: 31911
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      nodePort: 31911
      port: 53
      protocol: TCP
      targetPort: 53
    - name: web
      nodePort: 30366
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 32191
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: pihole
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations: {}
    generation: 17
    labels:
      app: pihole
      cluster: home-lab
      date: '2026-04-09'
      environment: production
      managed-by: terraform
    name: pihole
    namespace: pihole
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: pihole
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pihole
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - k8s3
        automountServiceAccountToken: true
        containers:
        - env:
          - name: TZ
            value: UTC
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                key: WEBPASSWORD
                name: pihole-web-password
                optional: false
          - name: DNS1
            value: 8.8.8.8
          - name: DNS2
            value: 8.8.4.4
          - name: DNSMASQ_LISTENING
            value: all
          - name: INTERFACE
            value: all
          - name: FTLCONF_dns_listeningMode
            value: all
          - name: FTLCONF_misc_etc_dnsmasq_d
            value: 'true'
          - name: VIRTUAL_HOST
            value: pihole.local.lan
          image: pihole/pihole:2024.07.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /admin
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: pihole
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
          - containerPort: 80
            name: web
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /admin
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/pihole
            mountPropagation: None
            name: pihole-data
          - mountPath: /etc/dnsmasq.d/02-local-dns.conf
            mountPropagation: None
            name: custom-dns
            subPath: 02-local-dns.conf
        dnsPolicy: ClusterFirstWithHostNet
        enableServiceLinks: true
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        shareProcessNamespace: false
        terminationGracePeriodSeconds: 30
        volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - configMap:
            defaultMode: 420
            name: pihole-custom-dns
            optional: false
          name: custom-dns
kind: List
metadata:
  resourceVersion: ''
