apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    labels:
      app: jellyfin
      cluster: home-lab
      date: '2026-04-09'
      environment: production
      managed-by: terraform
    name: jellyfin
    namespace: jellyfin
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.108.228.179
    clusterIPs:
    - 10.108.228.179
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      nodePort: 31786
      port: 8096
      protocol: TCP
      targetPort: 8096
    selector:
      app: jellyfin
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations: {}
    generation: 11
    labels:
      app: jellyfin
      cluster: home-lab
      date: '2026-04-09'
      environment: production
      managed-by: terraform
    name: jellyfin
    namespace: jellyfin
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jellyfin
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: '2026-04-17T19:32:44Z'
        creationTimestamp: null
        labels:
          app: jellyfin
      spec:
        automountServiceAccountToken: false
        containers:
        - env:
          - name: JELLYFIN_CONFIG_DIR
            value: /config
          - name: JELLYFIN_CACHE_DIR
            value: /cache
          image: jellyfin/jellyfin:10.10.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8096
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: jellyfin
          ports:
          - containerPort: 8096
            name: web
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8096
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
              - ALL
            privileged: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /dev/dri
            name: dri
          - mountPath: /config
            mountPropagation: None
            name: config
          - mountPath: /cache
            mountPropagation: None
            name: cache
          - mountPath: /media
            mountPropagation: None
            name: media
            readOnly: true
          - mountPath: /tmp
            mountPropagation: None
            name: tmp
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        nodeSelector:
          kubernetes.io/hostname: k8s-master
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        shareProcessNamespace: false
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /dev/dri
            type: Directory
          name: dri
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - hostPath:
            path: /media/sene/vidjo
            type: Directory
          name: media
        - emptyDir: {}
          name: tmp
kind: List
metadata:
  resourceVersion: ''
