apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.io/ip-allocated-from-pool: first-pool
    name: jellyseerr
    namespace: jellyseerr
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.111.190.121
    clusterIPs:
    - 10.111.190.121
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32119
      port: 5055
      protocol: TCP
      targetPort: 5055
    selector:
      app: jellyseerr
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations: {}
    generation: 1
    labels:
      app: jellyseerr
    name: jellyseerr
    namespace: jellyseerr
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jellyseerr
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jellyseerr
      spec:
        containers:
        - env:
          - name: TZ
            value: UTC
          image: fallenbagel/jellyseerr:latest
          imagePullPolicy: Always
          name: jellyseerr
          ports:
          - containerPort: 5055
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /app/config
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: config
kind: List
metadata:
  resourceVersion: ''
